# Site settings
title: Ehsan Irshad
twitter_username: ehsanirshad
name: Ehsan Irshad

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/ehsanirshad

#Any buzzword skills you want to include
skills:
 - C/C++
 - STL
 - Microservices
 - Distributed Computing / Storage
 - API design (REST FUL)
 - Kafka
 - Gradle
 - Java
 - SQL
 - REST
 - Technical Architecture
 - Machine learning

#Work experience is required
roles:
 - title: Architect
   start: 2019
   end: Ongoing
   employer: IBM
   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Scrum Lead
   start: 2015
   end: 2019
   employer: IBM
   description: Team of 14 engineers
 - title: Staff Software Engineer
   start: 2014
   end: 2015
   employer: IBM
   description: Test
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Computer Science (B.Sc.)
   date: 2005
   subject: Artificial Intelligence and Computer Science
   school: FAST NUCES (National University of Computer& Emerging Sciences Pakistan
