# Site settings
title: Ehsan Irshad
twitter_username: ehsanirshad
name: Ehsan Irshad

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/ehsanirshad

#Any buzzword skills you want to include
skills:
 - C/C++
 - STL
 - Microservices
 - Distributed Computing / Storage
 - API design (REST FUL)
 - Kafka
 - Gradle
 - Java
 - SQL
 - REST
 - Technical Architecture
 - Machine learning

#Work experience is required
roles:
 - title: Architect
   start: 2019
   end: Ongoing
   employer: IBM
   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Scrum Lead
   start: 2015
   end: 2019
   employer: IBM
   description: Team of 14 engineers
 - title: Staff Software Engineer
   start: 2014
   end: 2015
   employer: IBM
   description: Test
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Computer Science (B.Sc.)
   date: 2005
   subject: Artificial Intelligence and Computer Science
   school: FAST NUCES (National University of Computer& Emerging Sciences Pakistan
   
intro: |
  14 years of global experience in development with focus on architecture & design.<br>
  Directly managed team of 14 engineers in Singapore & India. Liaised with cross functional team of over 100 engineers, spread across Singapore, USA, Europe, India & Egypt.<br>
  Developed & supported platform to automate server lifecycle across 200 accounts with over 65,000 live servers across all GEOs.<br>
  Travelled to user sites in Mexico & Europe to provide technical mentoring.<br>
  Masters degree in machine learning & AI from NUS.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  AStar i2r, Singapore (1.5 years) â€“ Software Design Engineer	
  3DFM (A-Star i2r, 2011) 
  AStar is the leading research organization in Singapore with researchers from all across the world. This job was driven by my RA Ship for three months at NTU, Singapore. It takes one picture of subject and converts it into full 3D Model.
  Responsibilities
  Design, Development, Optimization
  Managed the team of 3 people, including a researcher.
  Development of iOS application
  Implemented Number of Image processing & Neural network techniques
  Technologies 
  C++, Objective C, STL, Multithreading, 
  OpenGL, OpenGL ES, Open Scene Graph, GLSL,
  MATLAB, SVN
  
  
